### ISSUE TITLE
Some updates are not recorded

### ISSUE THREAD

**Issue by tarasbilinsky** [nearform/temporal_tables#14]
Looks like the code marked with this comment
-- Ignore rows already modified in this transaction
makes it ignore some updates and not write in history.

As far as I understand, if I start a transaction and do multiple updates on a record then only the first change is written to history, and history of all other updates until transaction commit are lost.

**Comment by Codesleuth** [comment]
> As far as I understand, if I start a transaction and do multiple updates on a record then only the first change is written to history, and history of all other updates until transaction commit are lost.

I don't believe that is the expected behaviour. Every modification to the table should run the trigger, and this is agnostic of a single action or long-running transaction.

If this behaviour does not reflect that of the plugin at https://github.com/arkhipov/temporal_tables then we can legitimately post this as a bug; but I don't think this is the case. It's possible to write a test for that repo and copy-paste it here for verification (they run the same tests).

**Comment by paolochiodi** [comment]
I have checked the behaviour here and indeed we store only one change per transaction.

That is, if a row changes multiple times inside the same transaction, it is considered to be only one change happening to the row and hence only the state before the transaction starts is recorded in the history table.

I find this behaviour makes sense and, most importantly, it is consistent with the behaviour of the original c version of the extension, hence I'm keen to keep it as is.
