### ISSUE TITLE
Lagging behind

### ISSUE THREAD

**Issue by MikeGriffinReborn** [nearform/temporal_tables#23]
I am confused. You don't write out the inserted record to the history table upon insertion but only if an eventual update occurs? And then if I delete the record there is never a deleted event recorded in the history table? That is so strange. Am I seeing this right?

I would think I would have seen this?

1) INSERT INTO subscriptions (name, state) VALUES ('test1', 'inserted');
1) history table contains insert

2) UPDATE subscriptions SET state = 'updated' WHERE name = 'test1';
2) history table contains update

3) DELETE FROM subscriptions WHERE name = 'test1';
3) history table contains delete

Am I wrong in that this is not how it works?

**Comment by paolochiodi** [comment]
Hi.

The idea behind this extension is that history table contains all previous states of a record and the actual table contains the current version of the record.

So:

1. `INSERT INTO subscriptions (name, state) VALUES ('test1', 'inserted');`
2. `subscriptions` table contains `inserted`, `subscriptions_history` is empty
3. `UPDATE subscriptions SET state = 'updated' WHERE name = 'test1';`
4. `subscriptions` contains `updated`, `subscription_history` contains `inserted`
5. `DELETE FROM subscriptions WHERE name = 'test1';`
6. `subscriptions` is empty, `subscription_history` contains `inserted` and `updated`

The best way to think about it is that every change to a record in `subscriptions` will store the previous state of that record in `subscriptions_history`.

You can see the expected behaviour in the tests: https://github.com/nearform/temporal_tables/blob/master/test/expected/versioning.out#L128

This should be the same behaviour of the original c extension that we ported.
