### ISSUE TITLE
document migrations in README

### ISSUE THREAD

**Issue by gregwebs** [nearform/temporal_tables#5]
I had some questions that I thought would be good to document in the README

What is the migration strategy?
* apply the same schema migrations to the temporal table?
* don't do data migrations

What happens if a column is not created in the temporal table?

**Comment by paolochiodi** [comment]
@gregwebs sorry for being a bit late on this but the migration strategy is the one you actually suggest: apply migration to the temporal table as well.

If a column is not present in the temporal table it will be ignored, meaning that the value of that column won't be moved into the temporal table and that you'll loose the information (although that could be by design - if you don't need historical values for all the columns)

**Comment by paolochiodi** [comment]
I'll update the readme to clarify the behaviour.
